import { chromium } from "playwright-core";
import assert from "node:assert/strict";
import { mkdir, readFile, writeFile } from "node:fs/promises";

const base = (process.env.AUDIT_BASE_URL || "http://127.0.0.1:5173").replace(/\/$/, "");
const executablePath = process.env.CHROME_PATH || (process.platform === "win32" ? "C:/Program Files/Google/Chrome/Application/chrome.exe" : "/usr/bin/google-chrome");
const output = ".review/product";
await mkdir(output, { recursive: true });
const browser = await chromium.launch({ executablePath, headless: true });
const checks = [], errors = [], apiRequests = [];
const record = name => checks.push(name);
const sample = `<svg xmlns="http://www.w3.org/2000/svg" width="1280" height="720" viewBox="0 0 1280 720"><rect id="test-panel" x="260" y="190" width="340" height="200" fill="#eef2ff" stroke="#6243ce"/><circle id="test-circle" cx="900" cy="290" r="70" fill="#eee8ff"/><text id="test-text" x="430" y="290" text-anchor="middle" font-size="32" font-family="Arial">Editable figure</text><path id="test-path" d="M600 290H810" stroke="#6243ce" stroke-width="3"/></svg>`;
const waitReady = async page => { await page.waitForFunction(() => { const button = document.querySelector('button[aria-label="导出 SVG"], button[aria-label="Export SVG"]'); return button && !button.disabled; }); };
async function open(page, route) { await page.goto(base + route, { waitUntil: "networkidle" }); await page.evaluate(() => document.fonts.ready); }
const assertNoOverflow = async page => assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false);
try {
  const page = await browser.newPage({ viewport: { width: 1440, height: 900 } });
  await page.addInitScript(() => localStorage.setItem("autodraftman-language", "zh"));
  page.on("pageerror", error => errors.push(error.message));
  page.on("console", message => { if (message.type() === "error") errors.push(message.text()); });
  page.on("request", request => { if (new URL(request.url()).pathname.includes("/api/")) apiRequests.push(request.url()); });

  await open(page, "/pricing");
  assert.deepEqual(await page.locator(".product-nav a").allTextContents(), ["使用指南", "定价", "工作台"]);
  assert.deepEqual(await page.locator(".product-plan h2").allTextContents(), ["Sketch", "Folio", "Atlas"]);
  assert.equal(await page.locator('.product-plan img[src*="pricing-"]').count(), 3);
  assert.deepEqual(await page.locator(".product-plan-price strong").allTextContents(), ["9", "19", "39"]);
  await page.getByRole("button", { name: /年付/ }).click();
  assert.deepEqual(await page.locator(".product-plan-price strong").allTextContents(), ["7", "15", "31"]);
  assert.ok((await page.locator(".product-plan-billing").first().innerText()).includes("84"));
  record("Three original plan names and icons; monthly and annual prices");
  await page.locator(".product-plan").nth(1).getByRole("button", { name: "查看方案" }).click();
  assert.ok((await page.locator(".product-plan-message").innerText()).includes("不会收费"));
  await page.locator(".product-faq summary").first().click();
  assert.equal(await page.locator(".product-faq details").first().getAttribute("open"), "");
  record("Plan availability and working FAQ disclosures");
  await page.locator(".product-account").click();
  await page.waitForURL(/\/login$/);
  assert.equal(await page.locator(".product-login-providers .oauth-button:disabled").count(), 3);
  await page.getByRole("button", { name: /继续使用工作台/ }).click();
  await page.waitForURL(/\/workspace$/);
  assert.equal(await page.locator(".workspace-balance").count(), 0);
  assert.equal(await page.locator(".generate-button").isDisabled(), true);
  record("Static sign-in does not create an identity or a credit balance");

  await page.locator("#figure-prompt").fill("Show an encoder and decoder connected by a latent representation.");
  await page.locator('.product-nav a[href$="/docs"]').click();
  await page.locator('.product-nav a[href$="/workspace"]').click();
  assert.equal(await page.locator("#figure-prompt").inputValue(), "Show an encoder and decoder connected by a latent representation.");
  record("Draft is retained when navigating before the autosave delay");
  await page.getByRole("button", { name: "新建草稿", exact: true }).click();
  await page.locator("#figure-prompt").fill("A second local draft");
  await page.getByRole("button", { name: "新建草稿", exact: true }).click();
  await page.locator(".workspace-record-main").filter({ hasText: "A second local draft" }).click();
  assert.equal(await page.locator("#figure-prompt").inputValue(), "A second local draft");
  record("Creating and switching drafts preserves recent content");
  await page.locator('.workspace-record-delete').first().click();
  assert.equal(await page.getByRole("alertdialog").isVisible(), true);
  await page.getByRole("button", { name: "取消", exact: true }).click();
  assert.equal(await page.getByRole("alertdialog").count(), 0);
  record("Draft deletion offers a keyboard-accessible cancel action");
  await page.getByRole("tab", { name: "图片转 SVG", exact: true }).click();
  await page.locator("#reference-file").setInputFiles({ name: "reference.png", mimeType: "image/png", buffer: Buffer.from("iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+/NhoAAAAASUVORK5CYII=", "base64") });
  assert.ok((await page.locator(".reference-upload-copy").innerText()).includes("本地预览"));
  assert.equal(await page.locator(".product-workspace-source").count(), 1);
  await page.getByRole("button", { name: "我的 SVG", exact: true }).click();
  await page.locator(".product-documents").waitFor();
  assert.equal(await page.locator(".product-workspace-source:visible").count(), 0);
  await page.getByRole("button", { name: "原图预览", exact: true }).click();
  await page.locator(".product-source-review .product-workspace-source").waitFor({ state: "visible" });
  assert.equal(await page.locator(".product-workspace-source:visible").count(), 1);
  record("Reference image previews locally without an upload or authentication request");
  while (await page.locator(".workspace-record-delete").count() > 1) {
    await page.locator(".workspace-record-delete").last().click();
    await page.getByRole("alertdialog").getByRole("button", { name: "删除草稿", exact: true }).click();
    await page.getByRole("alertdialog").waitFor({ state: "hidden" });
  }
  await page.locator(".workspace-record-delete").click();
  await page.getByRole("alertdialog").getByRole("button", { name: "删除草稿", exact: true }).click();
  await page.getByRole("alertdialog").waitFor({ state: "hidden" });
  assert.equal(await page.locator(".workspace-record-delete").count(), 1);
  assert.equal(await page.locator("#figure-prompt").inputValue(), "");
  await page.reload({ waitUntil: "networkidle" });
  assert.equal(await page.locator("#figure-prompt").inputValue(), "");
  assert.equal(await page.locator(".workspace-record-delete").count(), 1);
  record("Deleting the last draft creates a blank draft without restoring deleted records");

  await page.locator('.product-nav a[href$="/docs"]').click();
  assert.equal(await page.locator(".product-guide-toc nav a").count(), 6);
  await page.locator('.product-guide-toc a[href="#guide-edit"]').click();
  await page.waitForFunction(() => document.querySelector('.product-guide-toc a[href="#guide-edit"]')?.getAttribute("aria-current") === "location");
  await page.locator('.product-guide-toc a[href="#guide-open"]').click();
  await page.waitForFunction(() => document.querySelector('.product-guide-toc a[href="#guide-open"]')?.getAttribute("aria-current") === "location");
  record("Guide section links and scroll tracking work in both directions");
  await page.locator('.product-guide-heading a[href$="/editor"]').click();
  await page.getByRole("button", { name: "新建空白画布", exact: true }).click();
  await waitReady(page);
  record("A real blank SVG canvas opens without a file or account");
  await page.locator('input[type="file"]').first().setInputFiles({ name: "editor-test.svg", mimeType: "image/svg+xml", buffer: Buffer.from(sample) });
  await waitReady(page);
  const frame = page.frameLocator(".figfox-svgedit-frame");
  await frame.locator("#test-panel").click({ position: { x: 20, y: 20 } });
  await page.getByRole("button", { name: /^填充:/ }).click();
  await page.getByRole("option", { name: "#24a37a", exact: true }).click();
  await page.waitForFunction(() => document.querySelector("iframe").contentDocument.querySelector("#test-panel").getAttribute("fill") === "#24a37a");
  await page.getByRole("button", { name: "撤销", exact: true }).click();
  await page.waitForFunction(() => document.querySelector("iframe").contentDocument.querySelector("#test-panel").getAttribute("fill") === "#eef2ff");
  await page.getByRole("button", { name: "重做", exact: true }).click();
  await page.waitForFunction(() => document.querySelector("iframe").contentDocument.querySelector("#test-panel").getAttribute("fill") === "#24a37a");
  record("Existing SVG engine edits an object and supports undo and redo");
  await page.locator('input[type="file"]').first().setInputFiles({ name: "broken.svg", mimeType: "image/svg+xml", buffer: Buffer.from("<svg><unclosed>") });
  await page.getByRole("alert").waitFor({ state: "visible" });
  assert.equal(await page.getByRole("alert").isVisible(), true);
  assert.equal(await frame.locator("#test-panel").getAttribute("fill"), "#24a37a");
  record("An invalid SVG import preserves the current document");

  await page.getByRole("button", { name: "适合画布", exact: true }).click();
  const download = page.waitForEvent("download");
  await page.getByRole("button", { name: "导出 SVG", exact: true }).click();
  const file = await download;
  await file.saveAs(output + "/edited.svg");
  const exported = await readFile(output + "/edited.svg", "utf8");
  assert.ok(exported.includes("#24a37a"));
  assert.ok(exported.includes("Editable figure"));
  assert.equal(file.suggestedFilename(), "editor-test-figfox.svg");
  record("Export contains the actual edits and the original text");
  await page.locator('.product-editor-back').click();
  await page.locator(".workspace-editor-link").click();
  await waitReady(page);
  assert.equal(await page.frameLocator("iframe").locator("#test-panel").getAttribute("fill"), "#24a37a");
  await page.reload({ waitUntil: "networkidle" });
  await waitReady(page);
  assert.equal(await page.frameLocator("iframe").locator("#test-panel").getAttribute("fill"), "#24a37a");
  record("Edited SVG survives route changes and a full page refresh");
  await page.getByRole("button", { name: "新建 SVG", exact: true }).click();
  assert.equal(await page.locator('.product-new-document-dialog').isVisible(), true);
  await page.getByRole("button", { name: "继续编辑", exact: true }).click();
  assert.equal(await page.frameLocator("iframe").locator("#test-panel").count(), 1);
  record("Starting a new document protects the current document with a choice");
  await page.getByRole("button", { name: "Switch to English" }).click();
  await waitReady(page);
  assert.equal(await page.frameLocator("iframe").locator("#test-panel").getAttribute("fill"), "#24a37a");
  await page.waitForTimeout(650);
  await page.screenshot({ path: output + "/editor-desktop.png" });
  record("Switching the editor language retains the SVG document");
  await assertNoOverflow(page);
  await page.close();

  const phone = await browser.newPage({ viewport: { width: 390, height: 844 }, isMobile: true, hasTouch: true });
  phone.on("pageerror", error => errors.push(error.message));
  phone.on("console", message => { if (message.type() === "error") errors.push(message.text()); });
  phone.on("request", request => { if (new URL(request.url()).pathname.includes("/api/")) apiRequests.push(request.url()); });
  await phone.addInitScript(() => localStorage.setItem("autodraftman-language", "zh"));
  await open(phone, "/workspace");
  await assertNoOverflow(phone);
  await phone.getByRole("button", { name: "打开菜单" }).click();
  await phone.keyboard.press("Escape");
  assert.equal(await phone.locator('.product-mobile-nav').count(), 0);
  await phone.getByRole("button", { name: "打开菜单" }).click();
  await phone.locator('.product-mobile-nav a[href$="/pricing"]').click();
  await phone.waitForURL(/\/pricing$/);
  assert.equal(await phone.locator('.product-mobile-nav').count(), 0);
  await assertNoOverflow(phone);
  await phone.waitForTimeout(650);
  await phone.screenshot({ path: output + "/pricing-mobile.png" });
  record("Mobile menu navigates and closes, without horizontal overflow");
  await open(phone, "/workspace");
  await phone.getByRole("button", { name: "历史记录", exact: true }).click();
  assert.equal(await phone.getByRole("dialog").isVisible(), true);
  await phone.keyboard.press("Tab");
  assert.equal(await phone.evaluate(() => !!document.activeElement.closest('[role="dialog"]')), true);
  await phone.keyboard.press("Escape");
  await phone.getByRole("dialog").waitFor({ state: "hidden" });
  record("Mobile draft drawer contains keyboard focus and closes on Escape");
  await open(phone, "/editor");
  await phone.getByRole("button", { name: "新建空白画布", exact: true }).click();
  await waitReady(phone);
  await assertNoOverflow(phone);
  await phone.getByRole("button", { name: "打开属性面板" }).click();
  await assertNoOverflow(phone);
  await phone.waitForTimeout(650);
  await phone.screenshot({ path: output + "/editor-mobile.png" });
  record("Mobile SVG canvas and inspector stay within the viewport");
  await phone.close();

  const recovery = await browser.newPage({ viewport: { width: 1440, height: 900 } });
  recovery.on("pageerror", error => errors.push(error.message));
  await recovery.addInitScript(() => localStorage.setItem("autodraftman-language", "zh"));
  await open(recovery, "/pricing");
  await recovery.evaluate(async markup => {
    await new Promise((resolve, reject) => {
      const request = indexedDB.open("figfox-local-editor", 1);
      request.onupgradeneeded = () => request.result.createObjectStore("documents");
      request.onerror = () => reject(request.error);
      request.onsuccess = () => {
        const database = request.result;
        const transaction = database.transaction("documents", "readwrite");
        transaction.objectStore("documents").put({ fileName: "grown-document.svg", markup, updatedAt: new Date().toISOString() }, "current");
        transaction.oncomplete = () => { database.close(); resolve(); };
        transaction.onerror = () => reject(transaction.error);
      };
    });
  }, sample.replace("</svg>", `<desc>${"local document ".repeat(400_000)}</desc><script>throw new Error('unsafe restoration')</script></svg>`));
  await open(recovery, "/editor");
  await waitReady(recovery);
  assert.equal(await recovery.frameLocator("iframe").locator("#test-panel").count(), 1);
  assert.equal(await recovery.frameLocator("iframe").locator("#svgcontent script").count(), 0);
  record("Local documents over the upload limit restore through the same SVG sanitizer");
  await recovery.close();

  const unavailableStorage = await browser.newPage();
  unavailableStorage.on("pageerror", error => errors.push(error.message));
  await unavailableStorage.addInitScript(() => {
    localStorage.setItem("autodraftman-language", "zh");
    const original = Storage.prototype.setItem;
    Storage.prototype.setItem = function (key, value) {
      if (key === "autodraftman-workspace-drafts-v1") throw new DOMException("Storage full", "QuotaExceededError");
      return original.call(this, key, value);
    };
  });
  await open(unavailableStorage, "/workspace");
  await unavailableStorage.locator("#figure-prompt").fill("A draft when browser storage is full");
  await unavailableStorage.getByText("本地保存失败，请保留草稿内容", { exact: true }).waitFor({ state: "visible" });
  record("Unavailable draft storage reports failure without crashing or claiming a save");
  await unavailableStorage.close();
  assert.deepEqual(errors, []);
  assert.deepEqual(apiRequests, []);
  await writeFile(output + "/checks.json", JSON.stringify({ base, checks, errors, apiRequests }, null, 2));
  console.log(JSON.stringify({ checks: checks.length, errors, apiRequests }));
} finally { await browser.close(); }
